'use server';

/**
 * @fileOverview AI-powered property description generator.
 *
 * - generatePropertyDescription - A function that generates a property description based on input details.
 * - PropertyDescriptionInput - The input type for the generatePropertyDescription function.
 * - PropertyDescriptionOutput - The return type for the generatePropertyDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PropertyDescriptionInputSchema = z.object({
  propertyType: z.string().describe('The type of property (e.g., house, apartment, condo).'),
  location: z.string().describe('The location of the property (city, neighborhood).'),
  numberOfBedrooms: z.number().describe('The number of bedrooms in the property.'),
  numberOfBathrooms: z.number().describe('The number of bathrooms in the property.'),
  squareFootage: z.number().describe('The square footage of the property.'),
  amenities: z.array(z.string()).describe('A list of amenities the property offers (e.g., swimming pool, gym, parking).'),
  uniqueFeatures: z.string().describe('A description of any unique or standout features of the property.'),
});

export type PropertyDescriptionInput = z.infer<typeof PropertyDescriptionInputSchema>;

const PropertyDescriptionOutputSchema = z.object({
  description: z.string().describe('A compelling description of the property generated by AI.'),
});

export type PropertyDescriptionOutput = z.infer<typeof PropertyDescriptionOutputSchema>;

export async function generatePropertyDescription(
  input: PropertyDescriptionInput
): Promise<PropertyDescriptionOutput> {
  return propertyDescriptionFlow(input);
}

const propertyDescriptionPrompt = ai.definePrompt({
  name: 'propertyDescriptionPrompt',
  input: {schema: PropertyDescriptionInputSchema},
  output: {schema: PropertyDescriptionOutputSchema},
  prompt: `You are an expert real estate copywriter. Generate a compelling and attractive property description based on the following details:

Property Type: {{propertyType}}
Location: {{location}}
Bedrooms: {{numberOfBedrooms}}
Bathrooms: {{numberOfBathrooms}}
Square Footage: {{squareFootage}}
Amenities: {{#each amenities}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Unique Features: {{uniqueFeatures}}

Write a description that highlights the key features and benefits of this property to attract potential buyers or renters.  Focus on creating a sense of luxury, comfort, and convenience. The description should be approximately 150-200 words.
`,
});

const propertyDescriptionFlow = ai.defineFlow(
  {
    name: 'propertyDescriptionFlow',
    inputSchema: PropertyDescriptionInputSchema,
    outputSchema: PropertyDescriptionOutputSchema,
  },
  async input => {
    const {output} = await propertyDescriptionPrompt(input);
    return output!;
  }
);
