import { Waves, Dumbbell, Film, Wine, Sunset, ConciergeBell, Layers, ChefHat, MountainSnow, Bath, Mountain, Thermometer, Gamepad2, View, Home, Shield, PersonStanding, CookingPot, Flower2, Coffee, type LucideIcon } from "lucide-react";

export const amenityIcons: { [key: string]: LucideIcon } = {
  'Pool': Waves,
  'Ocean View': Waves,
  'Private Gym': Dumbbell,
  'Home Theater': Film,
  'Wine Cellar': Wine,
  'Rooftop Terrace': Sunset,
  'Concierge': ConciergeBell,
  'Exposed Brick': Layers,
  'Chef\'s Kitchen': ChefHat,
  'Ski-in/Ski-out': MountainSnow,
  'Hot Tub': Bath,
  'Mountain View': Mountain,
  'Sauna': Thermometer,
  'Game Room': Gamepad2,
  '360° City View': View,
  'Private Pool': Waves,
  'Smart Home': Home,
  '24/7 Security': Shield,
  'Beach Access': Waves,
  'Yoga Deck': PersonStanding,
  'Outdoor Kitchen': CookingPot,
  'Surfboard Storage': Waves,
  'Zen Garden': Flower2,
  'Tea Room': Coffee,
  'Hinoki Bath': Bath,
  'Heated Floors': Thermometer,
};
