// Generated from apps/broker-os/lib/amenities.html by brokbuddy/scripts/sync-amenity-icons.mjs.
// Do not edit this file directly; update the HTML catalog and rerun the sync script.

export const DEFAULT_AMENITY_ICON_COMPONENT = "FaBuilding";

export const AMENITY_ICON_MAP = {
    "Swimming Pool": "FaPersonSwimming",
    "Shared Pool": "FaWaterLadder",
    "Private Pool": "FaWater",
    "Infinity Pool": "FaInfinity",
    "Kids Pool": "FaChildReaching",
    "Gymnasium": "FaDumbbell",
    "Shared Gym": "FaWeightHanging",
    "Spa": "FaSpa",
    "Sauna": "FaHotTubPerson",
    "Jacuzzi": "FaBath",
    "Yoga Area": "FaPersonRays",
    "Jogging Track": "FaPersonRunning",
    "Cycling Track": "FaPersonBiking",
    "Tennis Court": "FaTableTennisPaddleBall",
    "Basketball Court": "FaBasketball",
    "Football Ground": "FaFutbol",
    "Squash Court": "FaBaseball",
    "Badminton Court": "FaFeather",
    "Children's Play Area": "FaChildren",
    "Kids Playroom (Indoor)": "FaPuzzlePiece",
    "Private Beach Access": "FaUmbrellaBeach",
    "Rooftop Terrace": "FaPanorama",
    "Home Theater": "FaFilm",
    "Fully Equipped Gym": "FaDumbbell",
    "Gym or Health Club": "FaDumbbell",
    "Steam Room": "FaDoorOpen",
    "Private Jacuzzi": "FaBath",
    "Shared Spa": "FaSpa",
    "Children's Pool": "FaWaterLadder",
    "Private Gym": "FaDumbbell",
    "Lawn or Garden": "FaBarsProgress",
    "Barbeque Area": "FaFireBurner",
    "Cafeteria or Canteen": "FaUtensils",
    "Prayer Room": "FaMosque",
    "Dining in Building": "FaPlateWheat",
    "Centrally Air-Conditioned": "FaSnowflake",
    "Central Heating": "FaFireBurner",
    "Built-in Wardrobes": "FaDoorClosed",
    "Walk-in Closet": "FaShirt",
    "Study Room": "FaBookOpen",
    "Maids Room": "FaDoorOpen",
    "Driver's Room": "FaCar",
    "Storage Areas": "FaBox",
    "Utility Room": "FaWrench",
    "Laundry Room": "FaShirt",
    "In-unit Laundry": "FaSoap",
    "Powder Room": "FaSink",
    "Fully Fitted Kitchen": "FaKitchenSet",
    "Kitchen Appliances": "FaUtensils",
    "Gourmet Kitchen": "FaFireBurner",
    "Furnished": "FaCouch",
    "Semi-Furnished": "FaChair",
    "Unfurnished": "FaHouse",
    "Hardwood Floors": "FaLayerGroup",
    "Marble Floors": "FaBorderAll",
    "Exposed Brick": "FaCubes",
    "Floor-to-Ceiling Windows": "FaWindowMaximize",
    "Double Glazed Windows": "FaDoorOpen",
    "Fireplace": "FaFire",
    "Wine Cellar": "FaWineBottle",
    "Smart Home System": "FaHouseSignal",
    "High-Speed Internet Ready": "FaWifi",
    "Cable TV Ready": "FaTv",
    "Satellite TV Ready": "FaSatelliteDish",
    "Networked": "FaNetworkWired",
    "Covered Parking": "FaCar",
    "Basement Parking": "FaCarTunnel",
    "Multi-Storey Parking": "FaBuilding",
    "Visitor Parking": "FaCarSide",
    "2-Car Garage": "FaWarehouse",
    "Electric Vehicle Charging": "FaChargingStation",
    "Bicycle Parking": "FaBicycle",
    "Elevator": "FaElevator",
    "Balcony or Terrace": "FaBarsStaggered",
    "Service Elevators": "FaElevator",
    "Cleaning Services": "FaBroom",
    "Broadband Internet": "FaWifi",
    "Satellite/Cable TV": "FaTv",
    "24 Hours Concierge": "FaBellConcierge",
    "Parking Spaces": "FaSquareParking",
    "Electricity Backup": "FaBolt",
    "Flooring": "FaLayerGroup",
    "Vastu-compliant": "FaCompass",
    "Pets Allowed": "FaPaw",
    "Day Care Center": "FaHandHoldingHeart",
    "Shared Kitchen": "FaKitchenSet",
    "Laundry Facility": "FaJugDetergent",
    "ATM Facility": "FaMoneyBillWave",
    "24/7 Security": "FaShieldHalved",
    "CCTV Security": "FaVideo",
    "Access Control": "FaIdCardClip",
    "Intercom": "FaPhone",
    "Concierge Service": "FaBellConcierge",
    "Valet Parking": "FaCarOn",
    "Reception/Waiting Room": "FaCouch",
    "Lobby in Building": "FaBuildingUser",
    "Maintenance Staff": "FaScrewdriverWrench",
    "On-site Management": "FaUserTie",
    "Housekeeping": "FaBroom",
    "Housekeeping Services": "FaSprayCanSparkles",
    "Waste Disposal": "FaTrashCan",
    "Fire Safety System": "FaFireExtinguisher",
    "Emergency Exit": "FaDoorOpen",
    "Hotel Services": "FaHotel",
    "Serviced Apartment": "FaBed",
    "Security Staff": "FaUserShield",
    "First Aid Medical Center": "FaKitMedical",
    "Facilities for Disabled": "FaWheelchair",
    "Business Center": "FaBriefcase",
    "Private Garden": "FaLeaf",
    "Community Garden": "FaTree",
    "Landscaped Gardens": "FaSeedling",
    "Pet Friendly": "FaPaw",
    "Sea View": "FaWater",
    "Ocean View": "FaWater",
    "Marina View": "FaAnchor",
    "Golf Course View": "FaGolfBallTee",
    "City View": "FaCity",
    "Community View": "FaHouseChimneyWindow",
    "Park View": "FaTreeCity",
    "Landmark View": "FaMonument",
    "Waterfront": "FaWater",
    "Beachfront": "FaUmbrellaBeach",
    "Well-maintained Common Areas": "FaPeopleGroup",
    "Conference Room": "FaUsersViewfinder",
    "Kids Play Area": "FaChildReaching",
    "View": "FaPanorama",
    "Nearby Shopping Malls": "FaBagShopping",
    "View of Water": "FaWater",
    "View of Landmark": "FaMonument",
} as const satisfies Record<string, string>;

export type AmenityName = keyof typeof AMENITY_ICON_MAP;

export const AMENITY_LABEL_ALIAS_MAP = {
    "central-a-c": "Centrally Air-Conditioned",
    "central-ac": "Centrally Air-Conditioned",
    "air-con": "Centrally Air-Conditioned",
    "air-conditioning": "Centrally Air-Conditioned",
    "storage-room": "Storage Areas",
    "cctv-surveillance": "CCTV Security",
    "cctv": "CCTV Security",
    "reception-area": "Reception/Waiting Room",
    "service-elevator": "Service Elevators",
    "pool": "Swimming Pool",
    "gym": "Gymnasium",
    "garage": "2-Car Garage",
    "parking": "Parking Spaces",
    "garden": "Lawn or Garden",
    "beach-access": "Private Beach Access",
    "concierge": "Concierge Service",
    "security": "24/7 Security",
    "wifi": "Broadband Internet",
    "wi-fi": "Broadband Internet",
} as const satisfies Record<string, string>;

export function toAmenityLookupKey(value: string) {
    return value
        .trim()
        .replace(/\s+/g, ' ')
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/&/g, ' and ')
        .replace(/\+/g, ' plus ')
        .replace(/['\u2019]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

const CANONICAL_AMENITY_NAME_MAP = Object.fromEntries(
    Object.keys(AMENITY_ICON_MAP).map((amenityName) => [toAmenityLookupKey(amenityName), amenityName])
) as Record<string, AmenityName>;

export function getCanonicalAmenityName(amenityName: string) {
    const normalizedLabel = amenityName.trim().replace(/\s+/g, ' ');
    if (!normalizedLabel) return normalizedLabel;

    const lookupKey = toAmenityLookupKey(normalizedLabel);
    return CANONICAL_AMENITY_NAME_MAP[lookupKey]
        ?? AMENITY_LABEL_ALIAS_MAP[lookupKey as keyof typeof AMENITY_LABEL_ALIAS_MAP]
        ?? normalizedLabel;
}

export type AmenityIconComponentName =
    | (typeof AMENITY_ICON_MAP)[AmenityName]
    | typeof DEFAULT_AMENITY_ICON_COMPONENT;

export function getAmenityIconComponentName(amenityName: string): AmenityIconComponentName {
    const canonicalAmenity = getCanonicalAmenityName(amenityName);
    const exactMatch = AMENITY_ICON_MAP[canonicalAmenity as AmenityName];
    return exactMatch ?? DEFAULT_AMENITY_ICON_COMPONENT;
}

export const getAmenityIcon = getAmenityIconComponentName;
export const getAmenityIconPath = getAmenityIconComponentName;
