// Generated from apps/broker-os/lib/amenities.html by brokbuddy/scripts/sync-amenity-icons.mjs.
// Do not edit this file directly; update the HTML catalog and rerun the sync script.

export const DEFAULT_AMENITY_ICON_COMPONENT = "FaBuilding";

export const AMENITY_ICON_MAP = {
    "Swimming Pool": "/Residential Amenities icons/swimming pool.svg",
    "Shared Pool": "/Residential Amenities icons/Shared pool.svg",
    "Private Pool": "/Residential Amenities icons/private pool.svg",
    "Infinity Pool": "/Residential Amenities icons/Infinity pool.svg",
    "Kids Pool": "/Residential Amenities icons/Kids pool.svg",
    "Gymnasium": "/Residential Amenities icons/gymnasium.svg",
    "Shared Gym": "/Residential Amenities icons/shared gym.svg",
    "Spa": "/Residential Amenities icons/spa.svg",
    "Sauna": "/Residential Amenities icons/sauna.svg",
    "Jacuzzi": "/Residential Amenities icons/jacuzzi.svg",
    "Yoga Area": "/Residential Amenities icons/yoga area.svg",
    "Jogging Track": "/Residential Amenities icons/jogging track.svg",
    "Cycling Track": "/Residential Amenities icons/cycling track.svg",
    "Tennis Court": "/Residential Amenities icons/tennis court.svg",
    "Basketball Court": "/Residential Amenities icons/baskitbll court.svg",
    "Football Ground": "/Residential Amenities icons/football ground.svg",
    "Squash Court": "/Residential Amenities icons/Squash court.svg",
    "Badminton Court": "/Residential Amenities icons/Badminton court.svg",
    "Children's Play Area": "/Residential Amenities icons/children_s play area.svg",
    "Kids Playroom (Indoor)": "/Residential Amenities icons/kids playroom indoor.svg",
    "Private Beach Access": "/Residential Amenities icons/private beach access.svg",
    "Rooftop Terrace": "/Residential Amenities icons/rooftop terrsce.svg",
    "Home Theater": "/Residential Amenities icons/home theater.svg",
    "Fully Equipped Gym": "FaDumbbell",
    "Gym or Health Club": "/Residential Amenities icons/gym and health club.svg",
    "Steam Room": "/Residential Amenities icons/steam room.svg",
    "Private Jacuzzi": "/Residential Amenities icons/private jacuzzi.svg",
    "Shared Spa": "/Residential Amenities icons/shared spa.svg",
    "Children's Pool": "/Residential Amenities icons/childrens pool.svg",
    "Private Gym": "FaDumbbell",
    "Lawn or Garden": "/Residential Amenities icons/lawn and garden.svg",
    "Barbeque Area": "/Residential Amenities icons/barbeque area.svg",
    "Cafeteria or Canteen": "/Residential Amenities icons/cafeteria.svg",
    "Prayer Room": "/Residential Amenities icons/prayer room.svg",
    "Dining in Building": "/Residential Amenities icons/dining in building.svg",
    "Centrally Air-Conditioned": "/Residential Amenities icons/central AC.svg",
    "Central Heating": "/Residential Amenities icons/central heating.svg",
    "Built-in Wardrobes": "/Residential Amenities icons/builtin wardrobes.svg",
    "Walk-in Closet": "/Residential Amenities icons/walkin closet.svg",
    "Study Room": "/Residential Amenities icons/study room.svg",
    "Maids Room": "/Residential Amenities icons/maid room.svg",
    "Driver's Room": "/Residential Amenities icons/driver room.svg",
    "Storage Areas": "/Residential Amenities icons/storage room.svg",
    "Utility Room": "/Residential Amenities icons/utility room.svg",
    "Laundry Room": "/Residential Amenities icons/laundry room.svg",
    "In-unit Laundry": "/Residential Amenities icons/in-unit laundry.svg",
    "Powder Room": "/Residential Amenities icons/powder room.svg",
    "Fully Fitted Kitchen": "/Residential Amenities icons/fully fitted kitchen.svg",
    "Kitchen Appliances": "/Residential Amenities icons/kitchen appliances.svg",
    "Gourmet Kitchen": "/Residential Amenities icons/gourmet kitchen.svg",
    "Furnished": "/Residential Amenities icons/furnished.svg",
    "Semi-Furnished": "/Residential Amenities icons/semi-furnished.svg",
    "Unfurnished": "/Residential Amenities icons/unfurnished.svg",
    "Hardwood Floors": "/Residential Amenities icons/hardwood floors.svg",
    "Marble Floors": "/Residential Amenities icons/marble floors.svg",
    "Exposed Brick": "/Residential Amenities icons/exposed brick.svg",
    "Floor-to-Ceiling Windows": "/Residential Amenities icons/floor-to-ceiling window.svg",
    "Double Glazed Windows": "/Residential Amenities icons/double-glazed windows.svg",
    "Fireplace": "/Residential Amenities icons/fireplace.svg",
    "Wine Cellar": "/Residential Amenities icons/wine cellar.svg",
    "Smart Home System": "/Residential Amenities icons/smart home system.svg",
    "High-Speed Internet Ready": "/Residential Amenities icons/high-speed internet ready.svg",
    "Cable TV Ready": "/Residential Amenities icons/cable tv ready.svg",
    "Satellite TV Ready": "/Residential Amenities icons/satellite tv ready.svg",
    "Networked": "/Residential Amenities icons/networked.svg",
    "Covered Parking": "/Residential Amenities icons/covered parking.svg",
    "Basement Parking": "/Residential Amenities icons/basement oarking.svg",
    "Multi-Storey Parking": "/Residential Amenities icons/multi-storey parking.svg",
    "Visitor Parking": "/Residential Amenities icons/visitor parking.svg",
    "2-Car Garage": "/Residential Amenities icons/2-car garage.svg",
    "Electric Vehicle Charging": "/Residential Amenities icons/electric vehicle parking.svg",
    "Bicycle Parking": "/Residential Amenities icons/bycycle parking.svg",
    "Elevator": "/Residential Amenities icons/elevator.svg",
    "Balcony or Terrace": "/Residential Amenities icons/balcony.svg",
    "Service Elevators": "/Residential Amenities icons/serviced elivator.svg",
    "Cleaning Services": "/Residential Amenities icons/cleaning service.svg",
    "Broadband Internet": "/Residential Amenities icons/broadband internet.svg",
    "Satellite/Cable TV": "FaTv",
    "24 Hours Concierge": "/Residential Amenities icons/24 hour concerge.svg",
    "Parking Spaces": "/Residential Amenities icons/parking space.svg",
    "Electricity Backup": "/Residential Amenities icons/electricity backup.svg",
    "Flooring": "/Residential Amenities icons/flooring.svg",
    "Vastu-compliant": "/Residential Amenities icons/vastu compliant.svg",
    "Pets Allowed": "FaPaw",
    "Day Care Center": "/Residential Amenities icons/day care center.svg",
    "Shared Kitchen": "/Residential Amenities icons/shared kitchen.svg",
    "Laundry Facility": "FaJugDetergent",
    "ATM Facility": "/Residential Amenities icons/atm facility.svg",
    "24/7 Security": "/Residential Amenities icons/security.svg",
    "CCTV Security": "/Residential Amenities icons/cctv surveillance.svg",
    "Access Control": "/Residential Amenities icons/access control room.svg",
    "Intercom": "/Residential Amenities icons/intercom.svg",
    "Concierge Service": "/Residential Amenities icons/Concierge service.svg",
    "Valet Parking": "/Residential Amenities icons/valet parking.svg",
    "Reception/Waiting Room": "/Residential Amenities icons/reception weating room.svg",
    "Lobby in Building": "/Residential Amenities icons/lobby in building.svg",
    "Maintenance Staff": "/Residential Amenities icons/maintenance staff.svg",
    "On-site Management": "/Residential Amenities icons/on-sit managment.svg",
    "Housekeeping": "/Residential Amenities icons/housekeeping.svg",
    "Housekeeping Services": "/Residential Amenities icons/housekeeping services.svg",
    "Waste Disposal": "/Residential Amenities icons/waste disposal.svg",
    "Fire Safety System": "/Residential Amenities icons/fire safety system.svg",
    "Emergency Exit": "/Residential Amenities icons/emergency exit.svg",
    "Hotel Services": "/Residential Amenities icons/hotel services.svg",
    "Serviced Apartment": "/Residential Amenities icons/serviced appartment.svg",
    "Security Staff": "/Residential Amenities icons/security staff.svg",
    "First Aid Medical Center": "/Residential Amenities icons/first aid medical center.svg",
    "Facilities for Disabled": "/Residential Amenities icons/facilities for disabled.svg",
    "Business Center": "FaBriefcase",
    "Private Garden": "/Residential Amenities icons/private garden.svg",
    "Community Garden": "/Residential Amenities icons/community garden.svg",
    "Landscaped Gardens": "/Residential Amenities icons/landscaped garden.svg",
    "Pet Friendly": "/Residential Amenities icons/pet friendly.svg",
    "Sea View": "/Residential Amenities icons/sea view.svg",
    "Ocean View": "/Residential Amenities icons/ocean view.svg",
    "Marina View": "/Residential Amenities icons/marina view.svg",
    "Golf Course View": "/Residential Amenities icons/golf course view.svg",
    "City View": "/Residential Amenities icons/city view.svg",
    "Community View": "/Residential Amenities icons/community view.svg",
    "Park View": "/Residential Amenities icons/park view.svg",
    "Landmark View": "/Residential Amenities icons/landmark view.svg",
    "Waterfront": "/Residential Amenities icons/waterfront view.svg",
    "Beachfront": "/Residential Amenities icons/beachfront.svg",
    "Well-maintained Common Areas": "/Residential Amenities icons/well maintained common area.svg",
    "Conference Room": "/Residential Amenities icons/conference room.svg",
    "Kids Play Area": "/Residential Amenities icons/kids play area.svg",
    "View": "/Residential Amenities icons/view.svg",
    "Nearby Shopping Malls": "/Residential Amenities icons/nearby shoping area.svg",
    "View of Water": "/Residential Amenities icons/view of water.svg",
    "View of Landmark": "FaMonument",
} as const satisfies Record<string, string>;

export type AmenityName = keyof typeof AMENITY_ICON_MAP;

export const AMENITY_LABEL_ALIAS_MAP = {
    "central-a-c": "Centrally Air-Conditioned",
    "central-ac": "Centrally Air-Conditioned",
    "air-con": "Centrally Air-Conditioned",
    "air-conditioning": "Centrally Air-Conditioned",
    "storage-room": "Storage Areas",
    "cctv-surveillance": "CCTV Security",
    "cctv": "CCTV Security",
    "reception-area": "Reception/Waiting Room",
    "service-elevator": "Service Elevators",
    "pool": "Swimming Pool",
    "gym": "Gymnasium",
    "garage": "2-Car Garage",
    "parking": "Parking Spaces",
    "garden": "Lawn or Garden",
    "beach-access": "Private Beach Access",
    "concierge": "Concierge Service",
    "security": "24/7 Security",
    "wifi": "Broadband Internet",
    "wi-fi": "Broadband Internet",
} as const satisfies Record<string, string>;

export function toAmenityLookupKey(value: string) {
    return value
        .trim()
        .replace(/\s+/g, ' ')
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/&/g, ' and ')
        .replace(/\+/g, ' plus ')
        .replace(/['\u2019]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

const CANONICAL_AMENITY_NAME_MAP = Object.fromEntries(
    Object.keys(AMENITY_ICON_MAP).map((amenityName) => [toAmenityLookupKey(amenityName), amenityName])
) as Record<string, AmenityName>;

export function getCanonicalAmenityName(amenityName: string) {
    const normalizedLabel = amenityName.trim().replace(/\s+/g, ' ');
    if (!normalizedLabel) return normalizedLabel;

    const lookupKey = toAmenityLookupKey(normalizedLabel);
    return CANONICAL_AMENITY_NAME_MAP[lookupKey]
        ?? AMENITY_LABEL_ALIAS_MAP[lookupKey as keyof typeof AMENITY_LABEL_ALIAS_MAP]
        ?? normalizedLabel;
}

export type AmenityIconComponentName =
    | (typeof AMENITY_ICON_MAP)[AmenityName]
    | typeof DEFAULT_AMENITY_ICON_COMPONENT;

export function getAmenityIconComponentName(amenityName: string): AmenityIconComponentName {
    const canonicalAmenity = getCanonicalAmenityName(amenityName);
    const exactMatch = AMENITY_ICON_MAP[canonicalAmenity as AmenityName];
    return exactMatch ?? DEFAULT_AMENITY_ICON_COMPONENT;
}

export const getAmenityIcon = getAmenityIconComponentName;
export const getAmenityIconPath = getAmenityIconComponentName;
